version: '3'
services:
  db:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: Kiet0903602175
    ports:
      - "3306:3306"
    volumes:
      - ./db_volume/mysql_data:/var/lib/mysql
      - .:/depotV6
    stdin_open: true
    tty: true

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/depotV6
      - bundle:/usr/local/bundle
      - ./node_modules:/depotV6/node_modules
    tmpfs: /depotV6/tmp
    depends_on:
      - db
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
volumes:
  bundle:
  db: