version: '3'
services:
  db:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: Kiet0903602175
    ports:
      - "3306:3306"
    volumes:
      - ./db_volume/mysql_data:/var/lib/mysql
      - .:/depotV6
    stdin_open: true
    tty: true

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_MASTER_KEY: $DEPOTV6_RAILS_MASTER_KEY
    env_file:
      - .env
    volumes:
      - .:/depotV6
    ports:
      - "3000:3000"
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    depends_on:
      - web
    ports:
      - "8084:80"
volumes:
  bundle:
  db: