version: '3'
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db:/root/db
    stdin_open: true
    tty: true

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/depotV6
      - bundle:/usr/local/bundle
      - ./node_modules:/depotV6/node_modules
    tmpfs: /depotV6/tmp
    depends_on:
      - db
    tty: true
    stdin_open: true
    ports:
      - "127.0.0.1:3000:3000"
volumes:
  bundle:
  db: