version: '3'
services:
  db:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: Kiet0903602175
      MYSQL_DATABASE: depotV6_production
    ports:
      - "3306:3306"
    volumes:
      - ./db_volume/mysql_data:/var/lib/mysql
      - .:/depotV6
    stdin_open: true
    tty: true

  web: &web
    image: depotv6_web:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_MASTER_KEY: $DEPOTV6_RAILS_MASTER_KEY
    command: "bundle exec puma -C config/puma.rb"
    environment:
      RAILS_LOG_TO_STDOUT: "true"
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
volumes:
  bundle:
  db: